---
keys:
  - &host_nas_vm age1n582w08ffdd24aqrm5m4np4werlzlwc8cuwlr29ucjugx8v90fwqj9krjr
  - &work_mac age19049f7rnde3tjnl5vgnvhwhgmcxhzfx46jq8h5x7tncz8a2ulgmq3jug5v
  - &tback age1nz0td00jwmdxe9awtcuwy4sauq0gk7u8n78wrh2frue2gjqwuf6qfz4n2s
creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - gcp_kms:
          - resource_id: projects/taylor-cloud/locations/global/keyRings/sops/cryptoKeys/sops-key
        age:
          - age1q07mwz002uj9fe262u0uz4xhp2v0jqdppjpald0e259zx3u9yu5sx4klhy
          - age1ph42pqyrj6k3yyz2q3wtuelnxtx4cywqr38lajvhdduhamhtlufss83wne
          - age1m3cutzgsjkq6fct3mqkcvph0j3xs8yzzywhqtxwf263p9x7a5gwsjc5jg9
          - *host_nas_vm
          - age16wgxz0mlmah67jv9r38wvwadh0htjyxuvafsqzseqraaqam5w5ysrzl669
          - *work_mac
          - *tback
