---
creation_rules:
  - path_regex: nixos/.*secret\.sops\.ya?ml$
    gcp_kms: projects/taylor-cloud/locations/global/keyRings/sops/cryptoKeys/sops-key
    age: >-
      age1q07mwz002uj9fe262u0uz4xhp2v0jqdppjpald0e259zx3u9yu5sx4klhy,
      age1ph42pqyrj6k3yyz2q3wtuelnxtx4cywqr38lajvhdduhamhtlufss83wne
