cf-token: ENC[AES256_GCM,data:oPa6J9WzwAdkMCGW1YO2fE2K55uQmUUmBYx2j0AsQRakJ4HcnA==,iv:kRFO08G1e3cLNntKOsFMNa9pORjYyL0CJrKGKiMN1CA=,tag:qq+Wtc+BNNslb+RIFNiMSA==,type:str]
cf-email: ENC[AES256_GCM,data:joO8k1np10tpnJUPwi9v/4Q=,iv:d7UH76nS68NJx/y/SKyNuzi04vDeaoJD9n4CMOFR+IQ=,tag:o5R4VlhaXv6kCaol9WnC5Q==,type:str]
traefik-auth-file: ENC[AES256_GCM,data:wkpiHhVb8rJzG57VMlG+g7Sb8TBTO+DDfPQsQsjnUkIDp7ZXvxoDOwlphmI=,iv:1s3pCqqXR62DIGK5nrm1JSYK8EBRqoeAN3aTDzjOP5k=,tag:uRssUiuFFPu5h393ESTTVw==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/taylor-cloud/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-04-01T22:03:05Z"
          enc: CiQAXmmCQtYas1mGtxiSgZOAsxuNhv4kR76LpnFLX3UnUjNOKYkSSQA+M8UokPKdJqfElcdiVxaBZ1THLb/0pAjoFPYaKVT55/A+/9RCgn6FIN9upP9AEJhL/gnIuOproRUD43Qfz4MgdZS2JPAfSg0=
    age:
        - recipient: age1q07mwz002uj9fe262u0uz4xhp2v0jqdppjpald0e259zx3u9yu5sx4klhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a2E4QVlCSUhXRThJTnE3
            UU9lOWxtSmpvM2o0MlJhSEQxRVdrUUVkVzBVCkdFQ1BvVGtNdUFBZmluaVZuUmxR
            YkY4bENLRW9oNS9CdEJzYWc1Y2lRWEUKLS0tIERXclBrUzlleGIwWXJpa0RETWg4
            QVBDMVQ0N0VCV0pkdVhzNGtVdW1OVlEK5CDnM+a8ys+ikXSOrMdnCIJuaITozJzs
            Rc1VQDBmt4Bn7X78Ez31mPSMYIzUAGx2eQvXFsqa7UqHvrFxxjQp3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ph42pqyrj6k3yyz2q3wtuelnxtx4cywqr38lajvhdduhamhtlufss83wne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeXB0K1NKNFBBWUZ3cWIz
            a2JaNVpkdnRDWmpFOFVNbWgyMVlnenBTSjJJCnFES0ZpZXpzMUIvTlFCYmVuTEdN
            cE9kSkg1aURrZm05dHNtMW1zbFJPV0EKLS0tICtHdFZqMkh5MVBlcHg3amFHcy96
            b3p6eGdPUHhnL1hoMmFGMkFRb3l5cWcKLnShpkXYOT3EpUrZdP3lkRE0uWkM6aWk
            mjb03Ow+505KMvP7+5H33oQH/I+WMASqekaLesY8AzxEupvGtYPqjg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m3cutzgsjkq6fct3mqkcvph0j3xs8yzzywhqtxwf263p9x7a5gwsjc5jg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEczBlSVcwYURhYUZDbE5O
            RnloTUpIMU1qNEIyYklEQ1U4QzNCR3pKM0hZCjBaY09oOGNRRVJuZ2htNlNUQ3RL
            OWtWOVlQL2o1N3JEN1k1RmFwZS9BUEEKLS0tIHhDRXFvbUdzbE1sR0ZoS3JQU2lC
            Q0VRaHhDQXpRMU9tSGFPdXRoZ1BBT3cKZ8gafvdqvTGDK39ViOgZ76TiRjZLf+27
            XlGqhsi0ISDm6KsmF/egJrRE/Jk5r9sqf3pYiXXGBOqcugTrK3PiBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n582w08ffdd24aqrm5m4np4werlzlwc8cuwlr29ucjugx8v90fwqj9krjr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbWlxNG9UdU9ESSsvZDlU
            a3ZkQ3R5VkFoKzlVclVBWG9FSVpLaEoyOTNZCitxcU5CSThqV2NKOVpqeEtNbXN0
            akFaTWxGWVFPK0d6REcxWE1LR0phWTAKLS0tIEN5UnplNWZ3T2k5NCtITm0xUkxl
            UXZRdDBndEtNam5oanJiYXBXb3ZQVjAKCMacu9MSdTRn572Kqy2bUSx51rzzD8mD
            BOVEX6TzV4K5yvzMf9+6N+hWuAUcEL2JiAt3iVadu/bCY7HaQzS9Ag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16wgxz0mlmah67jv9r38wvwadh0htjyxuvafsqzseqraaqam5w5ysrzl669
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSk9NL2pUVVJ0UHhNdzUw
            U1JsbjdEYVpraU14czdkRDF6eDZCWUFqS0I0CktMMHZkMzNiaFJOV1psYjJ3SHp5
            RHlydzE5bllYa0hDZDZJT3AyZ09wWXcKLS0tIGc4L2ZRZCtBSGpXNDcwUnU4YjJu
            QmptYXJlM09YRXQrYWxXdkxVSTd5QWMK1IISTv7+brIvow4zaST1JkFjWvt8Vkun
            Js0dRfAHt6wt+mQLeSY8U5q7U9cgmFVGH7SvhokLtJTWeHlk+scqcg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19049f7rnde3tjnl5vgnvhwhgmcxhzfx46jq8h5x7tncz8a2ulgmq3jug5v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbU1sMzY4SnYrMlJ5MFVw
            UDlQSDhKMldrY1VpSktiUDFkTXllN3BBYVRnCndJa0RkMDJ6eVVEd3IzRjNsNXRZ
            VU45UFdONzFIT1pwRTVJSzZBb2pBM3cKLS0tIHFZNk9LTWZhbi8vYnpkQTZ0WEhk
            Sng0YzllUE9taEN1Zm5NSXlqcUlEbmsKHAx2pAdUeGxpcXHlSegBzvZXIlFMpsqY
            QH1GYgnwMO50uZ85nCpqXjANB+kSO4O+APYDspL8hyCEpy0STepDzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jvkfpdgegrr3p9v8s4vnld6hxd3qulfcwrn68uwav7m24hcnf5rqt28ah5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSkU4TXpqMkw2V3UwRVBj
            ODRqSGFqQzlleDdHSitJN1h5VGdtT3BkelE0ClAyaE5zcnlmSXRuSU5LamJZSzUr
            cVRGKy9iZ2lEVFRmNER4OWFmSnN5V1UKLS0tIEo2dngrTzdPVlhwdXZUaTNxUFpR
            ZUVoUXpQTEhSRnNsU2Rnb1hOeXhRY1EKkDwvpwHvlUVPB36RWi1xQUT1/qHV/ycN
            phO9mWTzM1cvKEKGU1DIA/vxAnX1uXVtlpGACLGVtN2jGNZ4oHEFcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fgvfcaptjl6f2dfr70v5kfarmlms6e89eqdg7eyxqj5k4w9zr5zs53wgxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMFB5UXVJNDB5UXJjZEt0
            TnltZG5SWVFqSElkaUJVOWU4MS84QU82cFVnCkVHczRQNDJxc1BFWjhUeFhENHlN
            b1lMK3NTK3FxemY3SS9QTHhMZFkzSDgKLS0tIFpOTmJTb2lDeEMwdTEvbWRZTWtU
            dVdPam51RUp5VzRBM0dMVFNGMFdkQ0kKrRf8zV/AhJQuMxwlMeie1rED2fCSGqjv
            iEb8ZYqEEut9MmmDXctwtO2fdGhJfU0LAeWnmGArtCGK/9plVihlKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ual2fd0gd9jsc5ns23938q5ahtqd8q0et7nk70seatl4z8d93usskjqele
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwamovMi9RR1VOUnVxNXBO
            RkQ5UVpDdk5kcEVubmZnMkNxam9OK0ovTndFClVzRHFyYVZ4T2d1cGp5NlBId0w5
            c1piZlhXVXQrMTAwL1JBazZUbTZUcDgKLS0tIExzUEpjREF6aFY0RjRHdk9MTzFJ
            QjFReFF4bVFyRXFIZ1UwT0hNVW9qNGsK6UfaXzysyLv3YU5Egy/5C8JwD55ihslJ
            sdWc6oDSjTHBbsZqF9y/tf3zNkRugSp+jBNog9wHyYlRH3fMH/ORdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ul3c8l632e7qug9cnt80u0c6kujnufrwvf0yy2fp86v59f9grcmqeehtd6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvY3BWd0JtdFRXNVhMOGpm
            ZjlHQnkyQkVEekRpVk40M0JQdk9QcjVkTmtvCnF0RjQrNHpDVDBzRmV1NGYzUW52
            WlhVa0NsSTBoWWUzNDRJcW9PaXk0MFUKLS0tIDUxWFpJNWJab1RjZ1dENUhERTBs
            bDNLWUFwcHRRcVhCWWphL21aMGorWDgK8zkfMEwHN2ye3sBJbmId7iXniNEH3KhT
            ey272nCFg70kAWpYz61dhRQi/k4hKkW+dy8VKm0ZTF6HVsDCb67wSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T22:03:05Z"
    mac: ENC[AES256_GCM,data:3iLXII8wqitUV494mQ2WMhDCEktAoKw0DZOTVmasRsb++k6R0pvQlmWghz4RgTe2cyNWLnzJDQP5v+TLJaqYW72u0ccDTouD73a+OEpy1JiiTx+A+CwPKhmeYwsRI+VyZNb4YHLilbuAri77ND3715oU2t9O3N9p8ohA8LzsmQs=,iv:QLbaG3f0qq3qzy/eqbRTYbvg5oaRmlrFSn6NnEsZTcg=,tag:6DH50raAUEMhue8VDrcCEQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
