cf-token: ENC[AES256_GCM,data:2TXy/f5iVe5Pe4+U513vc0qpfTxoeHGfdBV9j1rVhTDT8K9yQw==,iv:9kV4LgH24hbStxS+vtjKCSSOJ1EvsCHk3h4Wi2mtVWY=,tag:PewMf9V/VJOwECtfq+hZZQ==,type:str]
cf-email: ENC[AES256_GCM,data:EYO6CUq8ZOeS78p3ftZtD3M=,iv:B2b8VtXsLnRTvKTDl2nR6eZB88it6/81U44vaB8lBTc=,tag:EfMKOjt/W08zrXkhq8nHRw==,type:str]
traefik-auth-file: ENC[AES256_GCM,data:OifG7kk7aeKcnbuxDPbeMzSi4jNL98rOdMx1rT9Dw1qFVeA0B42F9iVpo8M=,iv:oeqYs0mePkmfwVECfRFhKEiMUSEqOQafFcJ/Rd0jLuQ=,tag:4bs7oXLdLV+djQLieXAhlQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/taylor-cloud/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-02-15T20:51:02Z"
          enc: CiQAXmmCQtiF/9T0Qk8za21FUrx5Da7crslF8y2swjAfBRArh84SSAA+M8Uo1jxD79Y++/Wa3BhJNoNz24JMJVlK+lmoJWZnrHEEC4Nad+oi20NRvpU6JhZ0TUh8OUyq+NYTRrD5hyrPfwDmlxN4DQ==
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q07mwz002uj9fe262u0uz4xhp2v0jqdppjpald0e259zx3u9yu5sx4klhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQVRwSFhmdm5zaHlEWW9k
            WG1PWkNjZFZxVExzNHNpRmN5WFhnVjh5S1hrCnV0UWhOdmtZVUVkVzBNRjBpM3BU
            YmZSZm5XUUk4L1BDNWtnOXdsV2NlRncKLS0tIGcvZVV6Z3NsMTFzRDNMNExVS2FJ
            M0RTSE5XZmMrbzlJeWdtczZwbWgvNE0K8iICzFakFuvL5EFDlVGquBNdcEsYonuP
            +W58gQ+x/CEVyYu+xLFW127+qmryqdCxtsYAcesxRKTpzRVMW/Lb4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ph42pqyrj6k3yyz2q3wtuelnxtx4cywqr38lajvhdduhamhtlufss83wne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEV1ZpUCt3Ty9Ybk5qLzky
            ZWFVZU8vMDJSMVlJS2RoVitmR3UyQlY3OGhFCk5YbWttUCthOThqUEc2SG9abDZD
            S09rZ25wdjRtQkZaM2lON1BhSTViT0UKLS0tIHVZSm1HZFluR1g1L244YU1NOUlo
            ZHY1eDNYVStNZXlNN0J0QXlHYnpYR00Kk5STNvMutXBzHQ4BmL6HwGpip30zGipi
            4U9QlS7/J/T/hOGuGSBYjxEyhBc0NUMe4g5qq23RbWMspUwZaVxnrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m3cutzgsjkq6fct3mqkcvph0j3xs8yzzywhqtxwf263p9x7a5gwsjc5jg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YU93TXozQUpGWTJYalIy
            VHB2NkVocTBNS0RDSDBIN2VvRnczajNiM0UwCm1HbE9ZdmlldmxvaTZQSVVMTTcx
            NTA1UitqVG5RbjBLZHU4cG10TURZOGsKLS0tIFVYRytERzM3azNheHRhUjZpelNV
            RE1YR3ZRaEw0M1BrVFdOUWpLYTRwckkK/kbyz0Wl0jxxr8EzNIr4c98MNmgAyzfM
            50K3q2p5HeclcIjSS3tHMpTcw0MqBqbd9U7PleIWUeyaN1A7wseyQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n582w08ffdd24aqrm5m4np4werlzlwc8cuwlr29ucjugx8v90fwqj9krjr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbjRSei9NYnFCSGcrTTY5
            ZGN6cGxCTXJvdTA0M2tub2s5UGZIcmpRZEdrClFYMC9WS3dkeFRGa0Rtb3JsTjAy
            cXRmV2hzN3JhR2g0cnVveTJvRGhuUjAKLS0tIEdvRExaVDJWcVZJS3B0emJmelZV
            eEl4NktxcmRxeHNKWEdUVWdIOSthRzQKHioxuUeo+6CWtaqTlP1EhTjtq9cyLpx9
            M3yJKK3oFzhIZ8hbuKr0tHL9W5AruuWdrU4hOWuOT97PdHwOqSLYOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16wgxz0mlmah67jv9r38wvwadh0htjyxuvafsqzseqraaqam5w5ysrzl669
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eng4MCtWUkdGNXh6UkVI
            QjFaTTRqdUxMeXlGUnlEZmxMV1B4blYxcVNFCmJML3dIVy9LV1JSaG52TWhSais5
            WllLNm8wR0w1TkpnVy9tV0xpc3QyNHcKLS0tIExQYUdqWi9sWHQ4Vmk5bGh5NG0v
            V0VYa2pOSjhmN2hyK0M2R3NoQVBQQzQKF4dVTy7ttcLr9CrqTiUPy1ZgkdZDOt1t
            ThXl72OesRv0qbZ336Pm5/LC8rJUnzGi+2MFUUiPUhUX2udPlcIc5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19049f7rnde3tjnl5vgnvhwhgmcxhzfx46jq8h5x7tncz8a2ulgmq3jug5v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncWdxVDU0M1hZYmVWTk9U
            N1EzOFpMU3QwRnovQmovYXBHV1YxVnRUeHpBCktMV2lsY2YrZHN6UXlPTktaQ0ZX
            MmR6cFhNRWNHWVpKdEZzT25JUk9idm8KLS0tIGdpSVJZM3l6SURTakd6Yi9aUDJI
            Skh5WS9HMGpLNHo5ZWZ0U3hqWnVVbUkKs9OVJOYDWPubQ7uLwD7eUjpuDb826FYF
            hE5YxW9iHhJmKu5eZV9FXL6hy9Cq8Zf12XBa0WgWcHv5NzD7wAqopg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jvkfpdgegrr3p9v8s4vnld6hxd3qulfcwrn68uwav7m24hcnf5rqt28ah5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuazQ0TnhPY215Qy9qeVhx
            MkpRN1ZCSzZFWGFvdzZ5K1dxdmhjamhTZGprCmRzU0d6dnN2aEhpdTBiOXRaUUJl
            Smt2QXpCcVdUU28zWElXWXZNY1FvQUkKLS0tIGI3OUdYQzlkY0ZSakdqVnp4YVl6
            WlJVVlQ3WVFack5DVG5OWFJXQ2lnVkUKoJCpfeFsmivsg98razRqNlZRYZ/ldvbG
            m5FflLQF4e9MXYPenVIpvk06xPXnmaqgpkFQdzXh6rGE9+24ObRukg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fgvfcaptjl6f2dfr70v5kfarmlms6e89eqdg7eyxqj5k4w9zr5zs53wgxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YythTElUZzN0WTBTakFs
            YllzZjIrRFdoT3c1WElZVHg3RU5jS1d6TGpBCi9sYldXNXdackpEUFlGVm1OS0tX
            QTAvSG1maHovTHpNK3R5bStkdmx3VXcKLS0tIFVpSzE3Q2xOci9yd3ZKazVKR09q
            S1Npc2tVZjg1WFJ1d1hEK2hmZHpDcE0K85lN+KBb+8YmbEz2ZXJMBLeeRBbbTC68
            FI/2BBPOx40k0yQbQgSKHVc4Zni6Mb0oeWCehdgj5E9eTy1YlCwruQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ual2fd0gd9jsc5ns23938q5ahtqd8q0et7nk70seatl4z8d93usskjqele
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYzFIU09EU0xlUGxpb3RF
            K0Y1Z0NyQ0xXMW1HSmxHeGdJTFZnUHpHNGprCkpuR25VZnpBQis4NFB6S05XSHJi
            RGF4WWpxYmRhV2QxdVVSeHFhVjRYS1EKLS0tIHVaNFZhdEtIamRRdzlIRkhPajRC
            T0VwdDBZM1hka2E0azVsOUUxM3VZdk0KQogOAtLe6q14PxDIjMxFo+jESmqD5Xy6
            aBKBdR0PqWoKOhschQP2JxepmUrNUUGgPO/4hM3ItunhRWmT8sThQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-15T20:51:02Z"
    mac: ENC[AES256_GCM,data:g7kMzNB3+/vGcBC9ufQjDuFuVEYRTx5KsJ1dStxbRdcnnopZ3TEqmN97V+rw3otm0AcWwvNv/zT9x7KN3x1+GyVD4S5R8erBLHtez8x8sICadM1CYD3q+QiewXPaxqfYqiSVx/fkvb0DQJlUEpfUaFrV/VXmnWc2nr9kbBOYsb8=,iv:KO1PoKEOm0XjxDpM4lWzMHdx5c4xPRH4E9MUXuIsDyk=,tag:qMuiwSPAr04kqdVWRZkZBQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
