# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  shcopy = {
    pname = "shcopy";
    version = "v0.1.5";
    src = fetchFromGitHub {
      owner = "aymanbagabas";
      repo = "shcopy";
      rev = "v0.1.5";
      fetchSubmodules = false;
      sha256 = "sha256-MKlW8HrkXCYCOeO38F0S4c8mVbsG/VcZ+oGFC70amqQ=";
    };
  };
  usage-cli = {
    pname = "usage-cli";
    version = "v6.7.1";
    src = fetchFromGitHub {
      owner = "jdx";
      repo = "usage";
      rev = "v6.7.1";
      fetchSubmodules = false;
      sha256 = "sha256-dnMDPREzXm6Tp5hbk100iCGJDlDqu1S36Dn7fH8eRuY=";
    };
  };
}
